puts "The students of Makers Academy"
puts "-----------------"
puts "Dr Hanisha Lecter"
puts "Darth Vader"
puts "Elon Musk"
puts "Jonny Dan"
puts "Steven Jonn"
print "Overall, we have "
print 5
print " excellent students"